### ISSUE TITLE
Automatically remove whitespace at the beginning and end of the url

### ISSUE THREAD

**Issue by vatbub** [bcantoni/rss-to-csv#1]
Hey there, thanks for creating such a simple yet powerful tool.
When using your tool, I accidentally left a space in front of the url, resulting in the following service request:
`https://gatos-jabra-buster.azurewebsites.net/api/RssToCsv?url=+https%3A%2F%2Fportal.mytum.de%2Fjobs%2Fwissenschaftler%2FasRss`

This obviously failed with the error message `Invalid 'url' parameter.`. I would therefore suggest to silently trim of any whitespace at the beginning and end of the url 😎

**Comment by bcantoni** [comment]
Thanks @vatbub for reporting this! Sorry it took me 8 months to respond but this is fixed now 😄
